### ISSUE TITLE
using --justbuild   throws TypeError: Cannot read property 'displaySauceDetails' 

### ISSUE THREAD

**Issue by rilopez** [apache/cordova-paramedic#111]
# Bug Report

## Problem

Got a null error when trying to run a build only execution 
```
cordova-paramedic --platform android --plugin cordova-plugin-inappbrowser --justbuild
```

### What is expected to happen?
Builds without errors

### What does actually happen?

It throws a TypeError

```
Skipping Appium tests: action = build ...
Completed tests at 4:06:35 PM
local-server: killing local file transfer server if it's up...
TypeError: Cannot read property 'displaySauceDetails' of null
    at /Users/ilopez/.nvm/versions/node/v10.15.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:119:40
    at process._tickCallback (internal/process/next_tick.js:61:11)
From previous event:
    at ParamedicRunner.run (/Users/ilopez/.nvm/versions/node/v10.15.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:103:6)
    at Object.exports.run (/Users/ilopez/.nvm/versions/node/v10.15.3/lib/node_modules/cordova-paramedic/lib/paramedic.js:489:19)
    at Object.<anonymous> (/Users/ilopez/.nvm/versions/node/v10.15.3/lib/node_modules/cordova-paramedic/main.js:189:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

### Command or Code

`cordova-paramedic --platform android --plugin cordova-plugin-inappbrowser --justbuild`

### Environment, Platform, Device
any

### Version information

- cordova :  `8.1.2 (cordova-lib@8.1.1)`
- cordova-pamedic: `0.6.0-dev`
- node: `10.15.3`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
Fixed in #110
