### ISSUE TITLE
cordova run --list --emulator --no-telemetry --no-update-notifier | grep ^iPhone | tail -n1 / Error: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by janpio** [apache/cordova-paramedic#123]
When updating the Xcode version used to build the app to Xcode 10.2, you get this error:

```
cordova-paramedic: running tests locally
cordova-paramedic: Choosing Target for iOS
running:
    cordova run --list --emulator --no-telemetry --no-update-notifier | grep ^iPhone | tail -n1
$ cordova run --list --emulator --no-telemetry --no-update-notifier | grep ^iPhone | tail -n1
Error: Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at Object.getSimulatorId (/Users/travis/build/apache/cordova-paramedic/lib/utils/utilities.js:91:27)
    at ParamedicTargetChooser.chooseTargetForIOS (/Users/travis/build/apache/cordova-paramedic/lib/ParamedicTargetChooser.js:142:33)
    at ParamedicTargetChooser.chooseTarget (/Users/travis/build/apache/cordova-paramedic/lib/ParamedicTargetChooser.js:43:30)
    at /Users/travis/build/apache/cordova-paramedic/lib/paramedic.js:411:39
From previous event:
    at ParamedicRunner.runLocalTests (/Users/travis/build/apache/cordova-paramedic/lib/paramedic.js:234:6)
    at ParamedicRunner.runTests (/Users/travis/build/apache/cordova-paramedic/lib/paramedic.js:348:21)
    at /Users/travis/build/apache/cordova-paramedic/lib/paramedic.js:95:21
From previous event:
    at ParamedicRunner.run (/Users/travis/build/apache/cordova-paramedic/lib/paramedic.js:81:6)
    at Object.exports.run (/Users/travis/build/apache/cordova-paramedic/lib/paramedic.js:489:19)
    at Object.<anonymous> (/Users/travis/build/apache/cordova-paramedic/main.js:189:15)
Completed tests at 12:40:48 PM
```

https://travis-ci.org/apache/cordova-paramedic/jobs/519233394

**Comment by janpio** [comment]
Probably related to: https://github.com/apache/cordova-paramedic/pull/120#issuecomment-482373114
Might also "hide" another issue: https://github.com/apache/cordova-paramedic/issues/98

**Comment by janpio** [comment]
Underlying problem was reported as https://github.com/apache/cordova-ios/issues/586 and fixed via https://github.com/apache/cordova-ios/pull/589. Will probably be released as `cordova-ios` 5.0.1 which will automatically be used then.

**Comment by timbru31** [comment]
Should we close this issue or wait for the next release?

**Comment by janpio** [comment]
Wait until fixed, so for the release.

**Comment by erisu** [comment]
There have been significant changes to the main branch that may make this ticket obsolete. While testing locally, I wasn't able to reproduce the issue. I believe it has been resolved, so I'm closing this as cannot reproduce and stale.
