### ISSUE TITLE
Where should I run the ios test?

### ISSUE THREAD

**Issue by WandyLau** [apache/cordova-paramedic#95]
I am new to Cordova and I want to know more about the test process.
I found this https://kerrishotts.github.io/pgday/workshops/2017/campp/testing.html#cordova-paramedic, in which some steps are provided to test a plugin.

I am still confused that where should I start the test. In the tests dir or in the root dir of plugin ? Or somewhere else? Please help me with this. Thanks.

**Comment by janpio** [comment]
Paramedic runs the tests outside of your application, it builds its own one during the testing setup - and then runs the tests that are defined for the plugin.

What command did you execute to get the result above? (Please also try to include the _complete_ output you get in the command line - often there are important info bits for contet)

A start would be to check out e.g. the camera plugin and execute your test command there - and see if this works. If it does, then the problem might be with your current plugin.

**Comment by WandyLau** [comment]
I just run ```cordova-paramedic cordova-paramedic --platform ios --plugin cordova-plugin-device```
This plugin is from https://github.com/apache/cordova-plugin-device.

```cordova-paramedic cordova-paramedic --platform ios --plugin cordova-plugin-device
cordova-paramedic: creating temp project at /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-59560aLfmeJOCwveo
cordova-paramedic: installing cordova-plugin-device
cordova-paramedic: installing cordova-plugin-device/tests
cordova-paramedic: installing plugin-test-framework
cordova-paramedic: starting local medic server ios
(node:59560) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
cordova-paramedic: writing medic log url to project
cordova-paramedic: setting app start page to test page
cordova-paramedic: adding platform
Error: cordova emulate return error code 1
output: Building for iPhone X Simulator
Building project: /private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-59560aLfmeJOCwveo/platforms/ios/HelloCordova.xcworkspace
	Configuration: Debug
	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-59560aLfmeJOCwveo/platforms/ios/build/emulator
    SDKROOT = iphonesimulator12.1
    SHARED_PRECOMPS_DIR = /private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-59560aLfmeJOCwveo/platforms/ios/build/sharedpch

Build settings from configuration file '/private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-59560aLfmeJOCwveo/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

No target specified for emulator. Deploying to iPhone-5, 10.2 simulator
/private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-59560aLfmeJOCwveo/platforms/ios/build/emulator/HelloCordova.app/Info.plist file not found.

result code is : 1```

**Comment by janpio** [comment]
Oh, wait a minute - how did you install paramedic? We haven't released the lastest fixes, that is why your output doesn't match mine at all. Best use the second method mentioned here: https://github.com/apache/cordova-paramedic#installation

**Comment by WandyLau** [comment]
I installed it with ```npm install -g cordova-parametic```
Then I install it with second cmd, git clone it and then ```npm link```. It is successful.
But I got the error below. The plugin is cordova-plugin-device.
```cordova-paramedic cordova-paramedic --platform ios --plugin ./cordova-plugin-device
cordova-paramedic: Will use the following cli: cordova
(node:78998) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
cordova-paramedic: creating temp project at /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-78998F165NL1SQuMG
$ cordova create /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-78998F165NL1SQuMG --no-telemetry --no-update-notifier
/private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-78998F165NL1SQuMG /Users/dong/repos/indy-ios/helloCordova/plugins
cordova-paramedic: installing plugins
cordova-paramedic: installing plugin /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-device --no-telemetry --no-update-notifier
$ cordova plugin add /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-device --no-telemetry --no-update-notifier
cordova-paramedic: installing plugin /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-78998F165NL1SQuMG/plugins/cordova-plugin-device/tests --no-telemetry --no-update-notifier
$ cordova plugin add /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-78998F165NL1SQuMG/plugins/cordova-plugin-device/tests --no-telemetry --no-update-notifier
cordova-paramedic: versions of installed plugins: 
$ cordova plugins --no-telemetry --no-update-notifier
cordova-paramedic: installing plugin /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-test-framework --no-telemetry --no-update-notifier
$ cordova plugin add /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-test-framework --no-telemetry --no-update-notifier
Error: Failed to install plugin : /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-test-framework --no-telemetry --no-update-notifier
Completed tests at 5:43:26 AM
Collecting logs for the devices.
It looks like there is no target to get logs from.
Uninstalling the app.
Error: Failed to install plugin : /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-test-framework --no-telemetry --no-update-notifier
    at PluginsManager.installSinglePlugin (/Users/dong/repos/cordova-paramedic/lib/PluginsManager.js:87:15)
    at PluginsManager.installPlugins (/Users/dong/repos/cordova-paramedic/lib/PluginsManager.js:37:14)
    at ParamedicRunner.installPlugins (/Users/dong/repos/cordova-paramedic/lib/paramedic.js:180:25)
    at ParamedicRunner.prepareProjectToRunTests (/Users/dong/repos/cordova-paramedic/lib/paramedic.js:152:10)
    at /Users/dong/repos/cordova-paramedic/lib/paramedic.js:76:21
    at _fulfilled (/Users/dong/repos/cordova-paramedic/node_modules/q/q.js:854:54)
    at /Users/dong/repos/cordova-paramedic/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/dong/repos/cordova-paramedic/node_modules/q/q.js:816:13)
    at /Users/dong/repos/cordova-paramedic/node_modules/q/q.js:877:14
    at runSingle (/Users/dong/repos/cordova-paramedic/node_modules/q/q.js:137:13)```

**Comment by WandyLau** [comment]
When I try the cordova-plugin-console plugin I got different error.
```cordova-paramedic: Will use the following cli: cordova
(node:79116) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
cordova-paramedic: creating temp project at /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh
$ cordova create /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh --no-telemetry --no-update-notifier
/private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh /Users/dong/repos/indy-ios/helloCordova/plugins
cordova-paramedic: installing plugins
cordova-paramedic: installing plugin /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-console --no-telemetry --no-update-notifier
$ cordova plugin add /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-console --no-telemetry --no-update-notifier
cordova-paramedic: installing plugin /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh/plugins/cordova-plugin-console/tests --no-telemetry --no-update-notifier
$ cordova plugin add /var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh/plugins/cordova-plugin-console/tests --no-telemetry --no-update-notifier
cordova-paramedic: versions of installed plugins: 
$ cordova plugins --no-telemetry --no-update-notifier
cordova-paramedic: installing plugin /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-test-framework --no-telemetry --no-update-notifier
$ cordova plugin add /Users/dong/repos/indy-ios/helloCordova/plugins/cordova-plugin-test-framework --no-telemetry --no-update-notifier
cordova-paramedic: installing plugin /Users/dong/repos/cordova-paramedic/paramedic-plugin --no-telemetry --no-update-notifier
$ cordova plugin add /Users/dong/repos/cordova-paramedic/paramedic-plugin --no-telemetry --no-update-notifier
cordova-paramedic: installing plugin /Users/dong/repos/cordova-paramedic/ios-geolocation-permissions-plugin --no-telemetry --no-update-notifier
$ cordova plugin add /Users/dong/repos/cordova-paramedic/ios-geolocation-permissions-plugin --no-telemetry --no-update-notifier
cordova-paramedic: setting app start page to test page
cordova-paramedic: adding platform ios (with:  --no-telemetry --no-update-notifier)
$ cordova platform add ios --no-telemetry --no-update-notifier
cordova-paramedic: successfully finished adding platform ios
cordova-paramedic: checking requirements for platform ios
$ cordova requirements ios --no-telemetry --no-update-notifier
cordova-paramedic: successfully finished checking requirements for platform ios
local-server: scanning ports from 7008 to 7208
local-server: port 7143 is available
local-server: starting local medic server
cordova-paramedic: writing medic log url to project http://127.0.0.1:7143
Start running tests at 5:46:08 AM
cordova-paramedic: running tests locally
cordova-paramedic: Choosing Target for iOS
running:
    cordova run --list --emulator --no-telemetry --no-update-notifier | grep ^iPhone | tail -n1
$ cordova run --list --emulator --no-telemetry --no-update-notifier | grep ^iPhone | tail -n1
running:
    instruments -s devices | grep ^iPhone
$ instruments -s devices | grep ^iPhone
cordova-paramedic: Setting required permissions.
cordova-paramedic: running command cordova run ios --no-telemetry --no-update-notifier --target iPhone-5 --emulator
$ cordova run ios --no-telemetry --no-update-notifier --target iPhone-5 --emulator
Completed tests at 5:46:17 AM
Collecting logs for the devices.
Running Command: cat /Users/dong/Library/Logs/CoreSimulator/8C184888-7671-4184-BD12-5BC9C0DEDA7C/system.log
$ cat /Users/dong/Library/Logs/CoreSimulator/8C184888-7671-4184-BD12-5BC9C0DEDA7C/system.log
Error: Failed to run command: cat /Users/dong/Library/Logs/CoreSimulator/8C184888-7671-4184-BD12-5BC9C0DEDA7C/system.log
Error: Failure code: 1
Uninstalling the app.
cordova-paramedic: Running command: xcrun simctl uninstall 8C184888-7671-4184-BD12-5BC9C0DEDA7C uninstall io.cordova.hellocordova
$ xcrun simctl uninstall 8C184888-7671-4184-BD12-5BC9C0DEDA7C uninstall io.cordova.hellocordova
Error: Failed to uninstall the app
Error: Error code: 164
cordova-paramedic: App uninstall timed out!
local-server: killing local file transfer server if it's up...
Building for iPhone 5 Simulator
Building project: /private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh/platforms/ios/HelloCordova.xcworkspace
	Configuration: Debug
	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh/platforms/ios/build/emulator
    SDKROOT = iphonesimulator12.1
    SHARED_PRECOMPS_DIR = /private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh/platforms/ios/build/sharedpch

Build settings from configuration file '/private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

/private/var/folders/kw/clrlzzcd3sz8tvpxpgbv3rv00000gn/T/tmp-791164SpwlDcLRgeh/platforms/ios/build/emulator/HelloCordova.app/Info.plist file not found.
```

As I found from the file /Users/dong/Library/Logs/CoreSimulator/CoreSimulator.log. There are so many lines like below:
```CoreSimulatorService[2522] <Error>: Error Domain=com.apple.CoreSimulator.SimError Code=162 "Incompatible device" UserInfo={NSLocalizedDescription=Incompatible device}```

It seems that cordova-paramedic use the iPhone-5 as default. How can change it to 12.0. I did not think I install iPhone-5. So I think this may be the problem. We need to test at latest version. The 5 is too old.

**Comment by janpio** [comment]
Damn, you arr having a terrible experience here. Sorry about that.
We seem to be using much older Xcode versions, and then it still works. So you are currently doing the work we will have to do one day anyway...

I do not know if there is a parameter to overwrite the simulator being used.

I found this code regarding the simulator: https://github.com/apache/cordova-paramedic/blob/91468049bb1d1def39beb5370ad62dba25f382da/lib/utils/utilities.js#L59-L121 Also this comand is executed in you log: `cordova run --list --emulator --no-telemetry --no-update-notifier | grep ^iPhone | tail -n1` What does it return? What about `cordova run --list --emulator --no-telemetry --no-update-notifier | grep ^iPhone`?

**Comment by WandyLau** [comment]
This is the return value of first one cmd: iPhone-5, 10.2
And ```iPhone-5s, 12.1
iPhone-5s, 10.2
iPhone-6, 12.1
iPhone-6, 10.2
iPhone-6-Plus, 12.1
iPhone-6-Plus, 10.2
iPhone-6s, 12.1
iPhone-6s, 10.2
iPhone-6s-Plus, 12.1
iPhone-6s-Plus, 10.2
iPhone-7, 12.1
iPhone-7, 10.2
iPhone-7-Plus, 12.1
iPhone-7-Plus, 10.2
iPhone-8, 12.1
iPhone-8-Plus, 12.1
iPhone-SE, 12.1
iPhone-SE, 10.2
iPhone-X, 12.1
iPhone-5, 10.2```

Ah it seems that iPhone-5 is installed. But My xcode version is 10.1. Does that matter?

**Comment by janpio** [comment]
No idea to be honest. It might, because of https://github.com/apache/cordova-ios/issues/407 :(

**Comment by WandyLau** [comment]
probably. I got this ```UseModernBuildSystem=0``` times when I have xcode 10. What if I want to have a try with xcode 10 how can I enable it in cordova-paramedic? Is it easy to do that?

**Comment by janpio** [comment]
Find the code that produces this output:
```
cordova-paramedic: Setting required permissions.
cordova-paramedic: running command cordova run ios --no-telemetry --no-update-notifier --target iPhone-5 --emulator
$ cordova run ios --no-telemetry --no-update-notifier --target iPhone-5 --emulator
```
and add the bit to the `run` command (afaik that is where it should be added).

**Comment by WandyLau** [comment]
OK. Thanks for the reply.
BTW, is there any other way to test the plugin? Some document will be fine.

**Comment by WandyLau** [comment]
@janpio Thanks very much for the doc. Really appreciate it.
